### PR TITLE
Supported the 11.5 of Xcode.

### PR DESCRIPTION
**Pull request by dogehk**
Related to issue #378

### CODE REVIEW

**Comment by kean** [comment]
Hi @dogehk. I'm also using Xcode 11.5 for development, and I tested Nuke on it. I don't see these issues with my setup. I'm wondering what the root cause is. We are using an initializer that works with [CIContextOption](https://developer.apple.com/documentation/coreimage/cicontextoption).

**Comment by saqibomer** [comment]
Issue persists in Xcode 12.4. 
9.0 and 10.0 have 
`public static var context = CIContext(options: [.priorityRequestLow: true])`
Instead of 
`public static var context = CIContext(options: [kCIContextPriorityRequestLow: true])`

**Comment by kean** [comment]
Hi, `kCIContextPriorityRequestLow` gets imported as [`.priorityRequestLow`](https://developer.apple.com/documentation/coreimage/cicontextoption/1620424-priorityrequestlow) in Swift. It's been like that for a couple of years now.

Could you describe how you compiling it?

**Comment by saqibomer** [comment]
It was due to build configuration. I had set older swift version in pod configuration.

**Pull request closed without merging**
