### PR TITLE
Fix issue #35

### PR DESCRIPTION
**Pull request by vkaramov**
I've fixed issue #35 by skipping further processing of images with Alpha channel.

### CODE REVIEW

**Comment by kean** [comment]
I actually thought about drawing all images in a single format that is best for rendering. I haven't figured out which one to use yet but kCGImageAlphaPremultipliedFirst looks good.

**Comment by vkaramov** [comment]
I have also tried it, but I got another warning ("Unsupported pixel description - 3 components, 64 bits-per-component)

**Comment by kean** [comment]
Ok, thanks a lot. I'll take a closer look when I get home :+1:

**Comment by kean** [comment]
Fixed in 9e24eca381aa5554bc8c78f60068e33ce1e7facc. Releasing v1.0.1 today.

**Pull request closed without merging**
