### PR TITLE
Add Swift version to podspec

### LINKED ISSUE #330: add SWIFT VERSION in Nuke.pobspec
Hello I'm getting this error :`Nuke` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Is it ok you add the SWIFT_VERSION in Nuke.pobspec?

### PR DESCRIPTION
**Pull request by dlackty**
This closes #330 

Ref: [CocoaPods's Podspec Syntax Reference](https://guides.cocoapods.org/syntax/podspec.html#swift_versions)

### CODE REVIEW

**Comment by kean** [comment]
Hi, @dlackty. Thanks for addressing this. I'm wondering whether it should specify an array of versions, including the latest ones.

**Comment by dlackty** [comment]
I was also surprised about the syntax, and found [some discussions about it](https://github.com/CocoaPods/CocoaPods/issues/7134). 

Anyway, maybe let's try `s.swift_versions = ['5.0', '5.1']`?

**Comment by kean** [comment]
Yes, I think we should use `swift_versions`. It seems that this syntax was created back in the days where every new Swift version had breaking changes.

**Comment by dlackty** [comment]
@kean Just updated the podspec again. Please have a look and let me know if there's any other concern.

**Pull request merged**
