### PR TITLE
add user agent

### PR DESCRIPTION
**Pull request by dlee121**

### CODE REVIEW

**Comment by dlee121** [comment]
sorry about this, I forked the repo for a personal project then created this PR without realizing where it was going... rookie mistake

**Comment by kean** [comment]
By the way, you can inject these kinds of headers using [`httpAdditionalHeaders`](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1411532-httpadditionalheaders) without modifying the framework.

**Comment by z-abhi** [comment]
@kean can you elaborate more, how I can set `User-Agentt` and `httpAdditionalHeaders` for all request?

**Comment by z-abhi** [comment]
@kean Thanks for the reply, appreciate it

**Pull request closed without merging**
