### PR TITLE
Swift PM: Add tools version to enable Xcode build

### PR DESCRIPTION
**Pull request by shpakovski**
Hi Alexander, it looks like your `master` branch is ready for tools v5. Proposed changes make a package working on Mac. Thanks!

### CODE REVIEW

**Comment by kean** [comment]
Hi, @shpakovski! This looks good, have you already tested this new package description? Is it possible to keep support for 4.2 packages? I'm not sure anyone is using it though.

**Comment by shpakovski** [comment]
> This looks good, have you already tested this new package description?

Sure, I use exactly this `Package.swift` in my project.

> Is it possible to keep support for 4.2 packages?

Could you please explain why this matters? We’re two months away from Xcode 11, and your codebase is totally future-proof. This library is more ready for production than competition, I suggest to keep it this way and “force-push” customers to use Swift 5.

> I'm not sure anyone is using it though.

Do you mean older Swift or the Swift PM itself, sorry?

**Comment by kean** [comment]
Alright, I think it's safe to assume that people who are ahead of the curve and are already using SwiftPM have also already migrated to Swift 5 as well. If there is someone who can't migrate just yet, they can keep using the previous version of Nuke.

> Do you mean the older version of Swift or the Swift PM itself, sorry?

Sorry, I wasn't clear enough, I meant SwiftPM.

I'm merging this PR, thanks for putting it together!

**Comment by shpakovski** [comment]
I can delete own fork now, thanks!

**Pull request merged**
